# Generated by Django 4.1.7 on 2023-03-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KAVIANEX', 'kavianex'), ('BINANCE', 'binance')], max_length=20)),
                ('api_key', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('secret_key', models.CharField(blank=True, default='', max_length=70, null=True)),
                ('test_net', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='BTCUSDT', max_length=10, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maker_exchange', to='amm.exchange')),
                ('taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taker_exchange', to='amm.exchange')),
            ],
        ),
    ]
