# Generated by Django 4.1.7 on 2023-03-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='test_net',
        ),
        migrations.AddField(
            model_name='exchange',
            name='main_net',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
