# Generated by Django 4.1.7 on 2023-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0003_exchange_remark_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
